import test from 'node:test';
import assert from 'node:assert/strict';
import {makeGame,step,hurt,collectItem,sanitizeRules,eliminate,surfaceY} from '../public/engine.js';
const roster=[{id:'a',name:'菠萝鸡'},{id:'b',name:'西瓜牛'}];
function scene(){const g=makeGame(roster,42,{mode:'coop'});g.platforms=[{id:80,x:180,baseX:180,y:300,w:500,type:'solid',layer:2}];for(const [i,p] of g.players.entries()){Object.assign(p,{x:350+i*70,y:300,ground:80,lastSafe:300});}return g;}
function frames(g,inputs,n){for(let i=0;i<n;i++)step(g,inputs);}
test('coop requires two players, gives each one pocket heart and keeps other rule defaults',()=>{assert.equal(sanitizeRules({mode:'coop'}).mode,'coop');assert.throws(()=>makeGame(roster.slice(0,1),1,{mode:'coop'}));assert.ok(scene().players.every(p=>p.heart&&p.hp===1));});
test('a teammate can rescue only nearby, on a platform, with a continuous hold',()=>{const g=scene(),[a,b]=g.players;a.hp=1;hurt(g,a,'测试');assert.ok(a.downed&&a.alive);b.x=650;frames(g,{b:{rescue:true}},10);assert.equal(a.reviveProgress,0);b.x=a.x;frames(g,{b:{rescue:true}},20);assert.ok(a.downed);frames(g,{},1);assert.equal(a.reviveProgress,0);frames(g,{b:{rescue:true}},38);assert.equal(a.downed,false);assert.equal(a.hp,1);assert.equal(b.stats.teamRescues,1);assert.equal(a.stats.receivedRescues,1);});
test('expired rescue and simultaneous downing end the team round',()=>{let g=scene();g.players[0].hp=1;hurt(g,g.players[0],'测试');frames(g,{},365);assert.equal(g.phase,'finished');assert.ok(g.result.every(p=>p.rank===1));g=scene();for(const p of g.players){p.hp=1;hurt(g,p,'测试');}step(g);assert.equal(g.phase,'finished');assert.ok(g.players.every(p=>!p.alive));});
test('heart supply is stored, eating respects cap, and pass heals only the catching teammate',()=>{const g=scene(),[a,b]=g.players;a.hp=3;step(g,{a:{eat:true}});assert.ok(a.heart);a.hp=2;step(g,{});step(g,{a:{eat:true}});assert.equal(a.hp,3);assert.equal(a.heart,false);collectItem(g,a,{type:'heart'});assert.equal(a.hp,3);assert.ok(a.heart);b.hp=1;frames(g,{a:{pass:true}},25);assert.equal(a.heart,false);assert.equal(a.stats.passes,1);assert.equal(b.hp,2);assert.equal(b.stats.catches,1);assert.equal(g.throws.length,0);});
test('missed heart expires and team score uses the smaller personal depth',()=>{const g=scene(),[a,b]=g.players;b.hp=3;frames(g,{a:{pass:true}},200);assert.equal(g.throws.length,0);assert.equal(b.stats.catches,0);assert.equal(g.teamMeters,Math.min(a.meters,b.meters));eliminate(g,b,'断线');step(g);assert.equal(g.phase,'finished');assert.equal(g.result[0].score,g.teamMeters*10);});
test('seesaw landing launches teammate on opposite end with cooldown',()=>{const g=scene(),[a,b]=g.players,f=g.platforms[0];f.type='seesaw';a.x=260;a.y=290;a.vy=600;a.ground=null;b.x=570;step(g);assert.ok(b.vy<0);assert.ok(f.launchAt>g.t);assert.notEqual(surfaceY({...f,tilt:.1},260),f.y);});
