import test from 'node:test';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {WebSocket} from 'ws';
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function newCode(port){const res=await fetch(`http://127.0.0.1:${port}/room`,{method:'POST'});return (await res.json()).code;}
function client(port,code,intent='join'){const ws=new WebSocket(`ws://127.0.0.1:${port}/ws?room=${code}&intent=${intent}`);const history=[];ws.on('message',d=>history.push(JSON.parse(d)));return {ws,history,send:m=>ws.send(JSON.stringify(m)),async wait(type,predicate=()=>true,after=0){const end=Date.now()+8000;while(Date.now()<end){const m=history.slice(after).find(m=>m.type===type&&predicate(m));if(m)return m;await delay(15);}throw new Error('Timeout '+type);}};}
test('12 clients: capacity, host authority, synchronization, elimination, replay and cleanup',{timeout:25000},async()=>{const port=3191;const server=spawn(process.execPath,['server.js'],{cwd:new URL('../',import.meta.url),env:{...process.env,PORT:String(port)},stdio:'pipe'});const clients=[];try{
 await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('error',reject);});
 const music=await fetch(`http://127.0.0.1:${port}/audio/space.mp3`);assert.equal(music.status,200);assert.match(music.headers.get('content-type'),/audio\/mpeg/);assert.ok((await music.arrayBuffer()).byteLength>100000);const credits=await fetch(`http://127.0.0.1:${port}/credits.html`);assert.equal(credits.status,200);
 const code=await newCode(port);const host=client(port,code,'create');clients.push(host);const id=(await host.wait('hello')).id;host.send({type:'create',name:'Host',look:{hat:2,eyes:4,color:9,width:85,fruit:6,animal:5}});const lobby=await host.wait('lobby');assert.equal(lobby.code,code);assert.equal(lobby.players[0].look.hat,2);assert.equal(lobby.players[0].look.fruit,6);assert.equal(lobby.players[0].look.animal,5);assert.equal(lobby.players[0].look.eyes,4);host.send({type:'appearance',look:{skin:2,hat:3,eyes:1,color:4,width:65,fruit:2,animal:3}});await host.wait('lobby',m=>m.players[0].look.hat===3);
 for(let i=1;i<12;i++){const c=client(port,code);clients.push(c);await c.wait('hello');c.send({type:'join',code,name:'相同的测试名字'});await c.wait('lobby');}
 const filled=await host.wait('lobby',m=>m.players.length===12);assert.equal(new Set(filled.players.map(p=>p.name)).size,12);
 const overflow=client(port,code);clients.push(overflow);await overflow.wait('hello');overflow.send({type:'join',code,name:'Overflow'});assert.match((await overflow.wait('error')).message,/已满/);
 const guest=clients[1];guest.send({type:'settings',rules:{mode:'timed',duration:30}});assert.match((await guest.wait('error')).message,/房主/);host.send({type:'settings',rules:{mode:'endless',duration:120}});await guest.wait('lobby',m=>m.rules.duration===120);guest.send({type:'start'});await delay(100);assert.equal(host.history.some(m=>m.type==='countdown'),false);
 host.send({type:'start'});await Promise.all(clients.slice(0,12).map(c=>c.wait('countdown')));
 const states=await Promise.all(clients.slice(0,12).map(c=>c.wait('state')));assert.ok(states.every(s=>s.game.seed===states[0].game.seed));assert.ok(states.every(s=>s.game.players.length===12));assert.ok(states.every(s=>s.game.players.find(p=>p.id===id).look.hat===3));assert.ok(states.every(s=>s.game.players.find(p=>p.id===id).look.fruit===2&&s.game.players.find(p=>p.id===id).look.animal===3));host.send({type:'appearance',look:{hat:5}});assert.match((await host.wait('error')).message,/比赛中/);
 assert.ok(states.every(s=>s.game.players.find(p=>p.id===id).look.skin===2));
 const before=states[0].game.players.find(p=>p.id===id).x;host.send({type:'input',right:true,x:99999});await host.wait('state',m=>m.game.players.find(p=>p.id===id).x>before+10);host.send({type:'input'});
 for(const c of clients.slice(1,12))c.ws.close();const result=await host.wait('state',m=>m.game.phase==='finished');assert.equal(result.game.result[0].id,id);assert.equal(result.game.result[0].rank,1);
 overflow.send({type:'join',code,name:'Next round'});await overflow.wait('lobby');host.send({type:'settings',rules:{mode:'timed',duration:30}});await host.wait('lobby',m=>m.rules.mode==='timed');const mark=host.history.length;host.send({type:'start'});await host.wait('countdown',()=>true,mark);const timed=await host.wait('state',m=>m.game.phase==='playing'&&m.game.players.length===2,mark);assert.deepEqual(timed.game.rules,{mode:'timed',duration:30});assert.ok(timed.game.items.every(i=>['heart','time','shield','poison'].includes(i.type)));assert.equal(timed.game.players[0].hp,1);
 host.ws.close();await overflow.wait('lobby',m=>m.host!==id);overflow.ws.close();await delay(100);const health=await(await fetch(`http://127.0.0.1:${port}/health`)).json();assert.equal(health.rooms,0);
 }finally{for(const c of clients)c.ws.terminate();server.kill('SIGTERM');}});
