import subprocess,json
from pathlib import Path
jobs={
'wukong-views':'''Original 16-bit pixel art Sun Wukong Monkey King character turnaround, exactly 2 columns and 2 rows of equal cells. Pure uniform light gray #dedede background, NO purple, NO magenta, no text, no grid, no ground shadow. Same heroic handsome monkey warrior in all four cells: front view, left profile, right profile, rear view. Full body, compact 3 heads tall heroic game proportions, expressive monkey face NOT a gorilla, ornate gold armor, red scarf and sash, black boots, phoenix feather golden crown, magical gold-tipped red staff. Sharp readable pixel clusters, limited arcade palette, consistent anatomy and clothing, generous cell margins. Based on the public domain Chinese literary Monkey King, original design not a movie adaptation. Production reference sheet for future animation.''',
'bajie-views':'''Original 16-bit pixel art Zhu Bajie pig warrior turnaround, exactly 2 columns and 2 rows equal cells. Uniform light gray #dedede background, NO purple NO magenta, NO text NO grid NO ground shadow. Four views of the SAME full body character: front, left profile, right profile, back. Stout anthropomorphic boar, expressive pig snout, dark brown lamellar armor, cream scarf, bronze bracers, large nine tooth iron farming rake. Humorous yet formidable fighting game enemy, 3 heads tall, crisp pixel clusters, consistent scale, generous margins. Original Chinese literary folklore design.''',
'landscapes':'''A production 16-bit pixel art background atlas, exactly 3 columns and 3 rows, nine equal panels, no characters, no bosses, no giant faces or statues, no text no borders. Each panel an original side-view fighting-game environment with open combat space, layered distant architecture, subtle depth, coherent lighting. Detailed pixel clusters not photorealistic. Top row: misty waterfall mountain monastery with tiny pagoda and rope bridge and restrained vegetation; abandoned rural market square with wooden stalls, windmill, reed canal and distant rice terraces; ancient sunken harbor with boat wrecks, sandstone bridge, scattered reeds and dunes. Middle row: volcanic foundry with cold basalt walls, suspended chains, old cranes and ONE distant lava channel; moonlit ruined courtyard with willow tree, pond, broken gate, stone lantern and a SINGLE small skull; red furnace palace with pipes, wooden scaffolds, pottery and ONE brazier. Bottom row: abandoned silk workshop garden with looms, overgrown trellis, hanging cloth and sparse corner cobwebs; storm mountain observatory with terraced steps, bells, distant sea of clouds and lightning; cosmic ruined observatory with floating stone paths, archways, broken armillary sphere, stars and subtle violet nebula. Mix natural and manmade objects within every panel, asymmetrical placement, no wallpaper-like repeated symbols. Keep floor around 80 percent height, dark but rich arcade palette.''',
'props':'''Production pixel art game prop spritesheet exactly 4 columns by 4 rows equal cells, isolated on uniform light gray #dedede background, no text no grid no shadows outside objects. Each prop fully inside its cell with generous margins, front-three-quarter game view, consistent crisp 16-bit style with dark outlines. Reading order sixteen DISTINCT objects: mossy stone lantern; broken wooden handcart; reed clump beside a clay pot; tattered red cloth on an old pole; hanging iron chain and hook; broken ceramic jars; bamboo crate of fruit; a single cracked skull beside a candle; a bronze bell suspended in a wooden frame; old wooden loom with cream silk; weathered stone arch fragment; overgrown tree roots on a rock; antique armillary sphere; fallen roof tiles with weeds; an abandoned iron anvil; a half sunken rowing boat. Original game environmental sprites, restrained colors. Not scenery, each is a separate usable sprite.''',
'effects':'''Production 16-bit pixel art animated VFX sheet, exactly FOUR columns and FOUR rows, sixteen equal cells. Uniform light gray #dedede background, no magenta purple backdrop, no text no grid. Row1 four sequential animation frames of a SMALL golden orange brazier flame on the same bronze cup. Row2 four sequential frames of a tiny hovering blue ghost lantern with gently changing flame. Row3 four sequential frames of a ragged crimson banner rippling in wind on same short pole. Row4 four sequential frames of a small cloud of pale mist curling and dissipating. All objects centered with consistent scale and baseline across their row, no cell overlap, crisp chunky pixel clusters dark outlines, clean cutout-ready game sprites. No repeated huge flames filling a background.'''
}
for key,prompt in jobs.items():
 Path('art-jobs/v2/'+key+'.prompt.txt').write_text(prompt)
 r=subprocess.run(['combos','asset','generate','--type','static_image','--prompt',prompt,'--async','--idempotency-key','man18-v2-scenery-'+key,'--json','--quiet'],capture_output=True,text=True)
 Path('art-jobs/v2/'+key+'.json').write_text(r.stdout);print(key,r.returncode,r.stdout[:400],r.stderr[:100],flush=True)
