from pathlib import Path
import subprocess
root=Path(__file__).parent
jobs={
'giants-a':['enormous emerald vine dragon head with wooden antlers and leafy whiskers, preparing then biting and spitting sharp physical leaves','colossal armored boar mouth with ivory tusks, opening jaws then snapping through wooden splinters','gigantic amber reptilian eye embedded in a sand-covered crocodile skull, opening lid then blasting sand and small pebbles'],
'giants-b':['giant obsidian bull horn and heavy armored forehead, pulling back then ramming with orange lava chunks','colossal ivory skeleton hand with antique wrist bracelets, curling then spreading long fingers and slamming','huge crimson lion guardian head with bronze ornaments, drawing breath then exhaling tangible orange flames'],
'giants-c':['gigantic jade spider face with jointed ivory mandibles, coiling then striking with pale silk threads and poison droplets','colossal golden eagle wing and talon, folding then sweeping forward with blue lightning feathers','giant violet octopus tentacle with gold star-shaped suckers, curling then uncoiling and lashing with floating meteor fragments']}
base='Production fantasy pixel arcade game SPRITE SHEET, exactly FOUR equal columns and THREE equal rows. Each row FOUR sequential action poses: anticipation, emerging, full strike, retracting. Pure uniform light gray #dedede background, no floor no text no grid lines. All creatures facing RIGHT, consistent scale per row, dark outlines, crisp chunky 16-bit pixel clusters, original Chinese mythology inspired design, full silhouette contained within each cell with generous margins. '
for key,rows in jobs.items():
 prompt=base+' '.join('Row '+str(i+1)+': '+v+'.' for i,v in enumerate(rows))
 (root/(key+'.prompt.txt')).write_text(prompt)
 r=subprocess.run(['combos','asset','generate','--type','static_image','--prompt',prompt,'--async','--idempotency-key','man18-world-v5-'+key,'--json','--quiet'],capture_output=True,text=True);(root/(key+'.json')).write_text(r.stdout);(root/(key+'.err')).write_text(r.stderr);print(key,r.returncode,r.stdout[:180],r.stderr[:120],flush=True)
prompt='Original fantasy 16-bit pixel game ITEM ICON ATLAS. Exactly FOUR columns THREE rows TWELVE equal cells. Pure uniform light gray #dedede background, no shadows no text no borders. One isolated detailed crisp pixel object per cell, full object inside margins, front three-quarter view. Reading order: 1 peach blossom wooden protective talisman; 2 golden rice grain pouch tied with red cord; 3 jade flask containing swirling sand; 4 ember-red pearl in a bronze fireproof cage; 5 small ivory ghost lantern with teal flame; 6 wooden chest holding three small iron fire wheels; 7 jade silk-cutting shuttle; 8 golden eagle feather talisman with blue crystal; 9 purple meteorite lotus seal; 10 ornate green bronze bow with three arrows; 11 red tasselled flame-tip spear; 12 carved violet demon-sealing gourd. Distinct silhouettes, tangible detailed materials, consistent art direction, usable collectible sprites.'
(root/'relics.prompt.txt').write_text(prompt)
r=subprocess.run(['combos','asset','generate','--type','static_image','--prompt',prompt,'--async','--idempotency-key','man18-world-v5-relics','--json','--quiet'],capture_output=True,text=True);(root/'relics.json').write_text(r.stdout);(root/'relics.err').write_text(r.stderr);print('relics',r.returncode,r.stdout[:180],r.stderr[:120],flush=True)
